import { useState } from "react";
import jsPDF from "jspdf";
import { Download, RefreshCw, Loader2, CheckCircle2, XCircle, Play } from "lucide-react";
import type { Report } from "@/lib/analysis";

interface AuditReportProps {
  report: Report;
  audioUrl?: string;
  onReset: () => void;
}

export function AuditReport({ report, audioUrl, onReset }: AuditReportProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const getMetricValue = (id: string) => {
    const metric = report.metrics?.find((m) => m.id === id);
    return metric ? metric.value : "N/A";
  };

  const lufsVal = getMetricValue("lufs");
  const snrVal = getMetricValue("snr");
  const peakVal = getMetricValue("peak");
  const vadVal = getMetricValue("vad");

  const isPassed = report.verdict === "pass";

  const handleExportPDF = () => {
    try {
      setIsGenerating(true);

      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const primaryColor: [number, number, number] = [15, 23, 42];
      const accentColor: [number, number, number] = [99, 102, 241];
      const textColor: [number, number, number] = [51, 65, 85];
      const lightBg: [number, number, number] = [248, 250, 252];
      const passColor: [number, number, number] = [34, 197, 94];
      const failColor: [number, number, number] = [239, 68, 68];

      pdf.setFillColor(...primaryColor);
      pdf.rect(0, 0, 210, 35, "F");

      pdf.setTextColor(255, 255, 255);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(22);
      pdf.text("MicCheck AI", 15, 18);

      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.text("Voice Quality Audit Report", 15, 26);
      pdf.text(new Date().toLocaleDateString("fr-FR"), 195, 20, { align: "right" });

      let y = 48;
      pdf.setTextColor(...primaryColor);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(14);
      pdf.text("Audit Details", 15, y);

      y += 8;
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      pdf.setTextColor(...textColor);
      pdf.text(`File Name: ${report.fileName}`, 15, y);
      pdf.text(`Duration: ${report.duration}`, 120, y);

      y += 12;
      const badgeColor = isPassed ? passColor : failColor;
      pdf.setFillColor(...badgeColor);
      pdf.roundedRect(15, y, 45, 10, 2, 2, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.text(isPassed ? "VERDICT: PASS" : "VERDICT: FAIL", 18, y + 6.5);

      y += 18;

      pdf.setFillColor(...lightBg);
      pdf.roundedRect(15, y, 85, 30, 3, 3, "F");
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(...accentColor);
      pdf.text("INTEGRATED LOUDNESS", 22, y + 10);
      pdf.setFontSize(15);
      pdf.setTextColor(...primaryColor);
      pdf.text(lufsVal, 22, y + 22);

      pdf.setFillColor(...lightBg);
      pdf.roundedRect(110, y, 85, 30, 3, 3, "F");
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(...accentColor);
      pdf.text("SIGNAL-TO-NOISE RATIO", 117, y + 10);
      pdf.setFontSize(15);
      pdf.setTextColor(...primaryColor);
      pdf.text(snrVal, 117, y + 22);

      y += 35;

      pdf.setFillColor(...lightBg);
      pdf.roundedRect(15, y, 85, 30, 3, 3, "F");
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(...accentColor);
      pdf.text("TRUE PEAK LEVEL", 22, y + 10);
      pdf.setFontSize(15);
      pdf.setTextColor(...primaryColor);
      pdf.text(peakVal, 22, y + 22);

      pdf.setFillColor(...lightBg);
      pdf.roundedRect(110, y, 85, 30, 3, 3, "F");
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(...accentColor);
      pdf.text("VOICE ACTIVITY", 117, y + 10);
      pdf.setFontSize(15);
      pdf.setTextColor(...primaryColor);
      pdf.text(vadVal, 117, y + 22);

      y += 40;
      pdf.setTextColor(...primaryColor);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(12);
      pdf.text("Summary", 15, y);

      y += 6;
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      pdf.setTextColor(...textColor);
      
      const splitSummary = pdf.splitTextToSize(report.summary, 180);
      pdf.text(splitSummary, 15, y);

      pdf.setFontSize(8);
      pdf.setTextColor(148, 163, 184);
      pdf.text(
        "Generated by MicCheck AI — Automatic Audio Quality Analyzer",
        105,
        285,
        { align: "center" }
      );

      pdf.save(`MicCheck_Audit_${Date.now()}.pdf`);
    } catch (error) {
      console.error("Erreur génération PDF:", error);
      alert("Erreur lors de la création du PDF.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="rounded-2xl border border-border bg-card p-6 shadow-xl">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold">{report.headline}</h2>
            <p className="text-sm text-muted-foreground">
              File: {report.fileName} ({report.duration})
            </p>
          </div>
          <div
            className={`flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-bold ${
              isPassed
                ? "border border-green-500/30 bg-green-500/10 text-green-500"
                : "border border-red-500/30 bg-red-500/10 text-red-500"
            }`}
          >
            {isPassed ? <CheckCircle2 className="size-4" /> : <XCircle className="size-4" />}
            {report.verdict.toUpperCase()}
          </div>
        </div>

        {/* Section Écoute Audio (Affiche le lecteur si disponible) */}
        {audioUrl && (
          <div className="mt-4 flex items-center gap-3 rounded-xl border border-primary/20 bg-primary/5 p-3">
            <Play className="size-4 text-primary shrink-0" />
            <audio src={audioUrl} controls className="h-8 w-full" />
          </div>
        )}

        <p className="mt-3 text-sm text-muted-foreground">{report.summary}</p>

        <div className="mt-6 grid grid-cols-2 gap-4">
          {report.metrics?.map((metric) => (
            <div
              key={metric.id}
              className="rounded-xl border border-border/50 bg-secondary/50 p-4"
            >
              <div className="flex justify-between items-center text-xs text-muted-foreground mb-1">
                <span>{metric.label}</span>
                <span className="font-mono">{metric.target}</span>
              </div>
              <p className="text-lg font-bold">{metric.value}</p>
              <p className="text-xs text-muted-foreground mt-1">{metric.note}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="flex items-center gap-3">
        <button
          type="button"
          onClick={handleExportPDF}
          disabled={isGenerating}
          className="inline-flex items-center gap-2 rounded-xl bg-gradient-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-glow transition-transform hover:-translate-y-0.5 cursor-pointer disabled:opacity-50"
        >
          {isGenerating ? (
            <>
              <Loader2 className="size-4 animate-spin" />
              Generating Report...
            </>
          ) : (
            <>
              <Download className="size-4" />
              Download Report
            </>
          )}
        </button>

        <button
          type="button"
          onClick={onReset}
          className="inline-flex items-center gap-2 rounded-xl border border-border bg-secondary px-4 py-2.5 text-sm font-semibold text-foreground transition-colors hover:bg-secondary/80 cursor-pointer"
        >
          <RefreshCw className="size-4" />
          New Audit
        </button>
      </div>
    </div>
  );
}
