import { useState } from "react";
import jsPDF from "jspdf";
import { Download, RefreshCw, Loader2, CheckCircle2, XCircle } from "lucide-react";
import type { Report } from "@/lib/analysis";

interface AuditReportProps {
  report: Report & Record<string, any>; // Permet de lire des propriétés flexibles
  onReset: () => void;
}

export function AuditReport({ report, onReset }: AuditReportProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  // Extraire les valeurs avec des fallbacks selon la structure de ton objet `report`
  const lufsVal = report.lufs ?? report.lufsIntegrated ?? report.metrics?.lufs ?? "N/A";
  const snrVal = report.snr ?? report.snrRatio ?? report.metrics?.snr ?? "N/A";
  const status = report.status ?? report.verdict ?? (report.passed ? "PASS" : "FAIL");
  const isPassed = String(status).toUpperCase().includes("PASS") || report.passed === true;

  const handleExportPDF = () => {
    try {
      setIsGenerating(true);

      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      // Colors
      const primaryColor: [number, number, number] = [15, 23, 42];
      const accentColor: [number, number, number] = [99, 102, 241];
      const textColor: [number, number, number] = [51, 65, 85];
      const lightBg: [number, number, number] = [248, 250, 252];
      const passColor: [number, number, number] = [34, 197, 94];
      const failColor: [number, number, number] = [239, 68, 68];

      // Header
      pdf.setFillColor(...primaryColor);
      pdf.rect(0, 0, 210, 35, "F");

      pdf.setTextColor(255, 255, 255);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(22);
      pdf.text("MicCheck AI", 15, 18);

      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.text("Voice Quality Audit Report", 15, 26);
      pdf.text(new Date().toLocaleDateString("fr-FR"), 195, 20, { align: "right" });

      // File Details
      let y = 48;
      pdf.setTextColor(...primaryColor);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(14);
      pdf.text("Audit Details", 15, y);

      y += 8;
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      pdf.setTextColor(...textColor);
      pdf.text(`File Name: ${report.fileName || "Live Recording"}`, 15, y);

      // Status Badge (PASS / FAIL)
      y += 12;
      const badgeColor = isPassed ? passColor : failColor;
      pdf.setFillColor(...badgeColor);
      pdf.roundedRect(15, y, 40, 10, 2, 2, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(10);
      pdf.text(isPassed ? "VERDICT: PASS" : "VERDICT: FAIL", 18, y + 6.5);

      // Metrics Cards
      y += 18;

      // Card 1: Loudness
      pdf.setFillColor(...lightBg);
      pdf.roundedRect(15, y, 85, 30, 3, 3, "F");
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(...accentColor);
      pdf.text("LOUDNESS (LUFS)", 22, y + 10);
      pdf.setFontSize(16);
      pdf.setTextColor(...primaryColor);
      pdf.text(`${lufsVal} LUFS`, 22, y + 22);

      // Card 2: SNR
      pdf.setFillColor(...lightBg);
      pdf.roundedRect(110, y, 85, 30, 3, 3, "F");
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(...accentColor);
      pdf.text("SNR RATIO", 117, y + 10);
      pdf.setFontSize(16);
      pdf.setTextColor(...primaryColor);
      pdf.text(`${snrVal} dB`, 117, y + 22);

      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(148, 163, 184);
      pdf.text("Generated by MicCheck AI — Automatic Audio Quality Analyzer", 105, 285, { align: "center" });

      pdf.save(`MicCheck_Audit_${Date.now()}.pdf`);
    } catch (error) {
      console.error("Erreur PDF:", error);
      alert("Erreur lors de la génération du PDF.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Visual Report */}
      <div className="rounded-2xl border border-border bg-card p-6 shadow-xl">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold">Voice Audit Summary</h2>
            <p className="text-sm text-muted-foreground">File: {report.fileName}</p>
          </div>
          <div
            className={`flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-bold ${
              isPassed
                ? "border border-green-500/30 bg-green-500/10 text-green-500"
                : "border border-red-500/30 bg-red-500/10 text-red-500"
            }`}
          >
            {isPassed ? <CheckCircle2 className="size-4" /> : <XCircle className="size-4" />}
            {isPassed ? "PASSED" : "FAILED"}
          </div>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-4">
          <div className="rounded-xl border border-border/50 bg-secondary/50 p-4">
            <span className="text-xs text-muted-foreground">Loudness (LUFS)</span>
            <p className="text-lg font-bold">{lufsVal} LUFS</p>
          </div>
          <div className="rounded-xl border border-border/50 bg-secondary/50 p-4">
            <span className="text-xs text-muted-foreground">SNR Ratio</span>
            <p className="text-lg font-bold">{snrVal} dB</p>
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-3">
        <button
          type="button"
          onClick={handleExportPDF}
          disabled={isGenerating}
          className="inline-flex items-center gap-2 rounded-xl bg-gradient-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-glow transition-transform hover:-translate-y-0.5 cursor-pointer disabled:opacity-50"
        >
          {isGenerating ? (
            <>
              <Loader2 className="size-4 animate-spin" />
              Generating Report...
            </>
          ) : (
            <>
              <Download className="size-4" />
              Download Report
            </>
          )}
        </button>

        <button
          type="button"
          onClick={onReset}
          className="inline-flex items-center gap-2 rounded-xl border border-border bg-secondary px-4 py-2.5 text-sm font-semibold text-foreground transition-colors hover:bg-secondary/80 cursor-pointer"
        >
          <RefreshCw className="size-4" />
          New Audit
        </button>
      </div>
    </div>
  );
}
